### PR TITLE
Add building/installing instructions

### PR DESCRIPTION
**Pull request by wezm**

### CODE REVIEW

**Comment by fgsch** [comment]
Thanks for the PR.  Just to let you know, I'm not ignoring this. 
I'm trying to find a common format that I'm comfortable with for all my modules. Once that happens I will document requirements, how to build and whatnot.

**Comment by fgsch** [comment]
I've now added some instructions to build and install the module along the requirements and some other things.  I believe this should cover the PR. Sorry it took so long.

If you have time to check it I'd appreciate your feedback.

**Comment by wezm** [comment]
Looks good to me :+1:

**Comment by fgsch** [comment]
Great. Thanks for checking.

**Pull request closed without merging**
